### ISSUE TITLE
Trained model drives car into the water

### ISSUE THREAD

**Issue by Wanjiru-Ngugi** [llSourcell/How_to_simulate_a_self_driving_car#28]
I have cloned this repo, generated my own data using the training mode on the simulator and used these images to retrain my model. When I run drive.py, the car drives into the water after a while even though I did not drive into the water while training. What could be the issue? 

I have no errors on my terminal while running model.py and drive.py.

What could be the issue?

**Comment by ghost** [comment]
have you fixed this issue? having the same problem :/

**Comment by Wanjiru-Ngugi** [comment]
I solved it by deleting the __pycache__ folder.

**Comment by SohailSayed** [comment]
I'm having the same problem, but deleting the folder doesn't help
