### ISSUE TITLE
Issue with importing cv2.

### ISSUE THREAD

**Issue by shuvamklu** [llSourcell/How_to_simulate_a_self_driving_car#35]
@AbhishekPatnaik While trying to run the pre-trained model.I am getting the error on first line of the util.py.
`import cv2,os`
The error showing is..
`
ImportError: /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates`

how to solve this???

**Comment by Stormwaker** [comment]
You've closed this issue. Does this mean that you've found the solution for it? Could you share it? I'm struggling with it right now...
