### ISSUE TITLE
'driving_log.csv' not found

### ISSUE THREAD

**Issue by tanaymitkari1** [llSourcell/How_to_simulate_a_self_driving_car#37]
I have "driving_log.csv" file in the same folder still getting an error. 
FileNotFoundError: File b'D:\\Projects\\Artificial Intelligance\\UdacitySDC\\data\\driving_log.csv' does not exist

**Comment by bhuvantej** [comment]
Make sure that "driving_log.csv" file in the folder where you downloaded your simulator(Udacity-simulator).
In my case, it was in Downloads/simulator-linux/driving_log.csv.

**Comment by tanaymitkari1** [comment]
solved !
I created data folder and pasted the driving_log.csv file in it.

**Comment by IkrameBeggar** [comment]
I am getting the same error as yours can you help me with that please?
