### ISSUE TITLE
csv file is not present in repo

### ISSUE THREAD

**Issue by Madhu009** [llSourcell/How_to_simulate_a_self_driving_car#9]
can anyone please provide the data file driving_log.csv

**Comment by grep-rohan** [comment]
Just `driving_log.csv` is not enough. You also need the images. You can generate the data yourself using the unity simulator. You can download it for Windows, Linux and Mac from [this link](https://github.com/udacity/self-driving-car-sim#avaliable-game-builds-precompiled-builds-of-the-simulator).

To generate data, start up the downloaded simulator, choose a scene and press the Training Mode button. Then, press R to choose directory for storing the data. After choosing directory press R to start recording. Drive for around 5 laps and press R again to finish capturing data.
